const galleryImages = [
  {
    title: 'Watercolour portrait of significant other',
    imageClass: 'watercolour',
    full: '04.jpg',
    thumbs: '04.png',
  },
  {
    title: 'Birthday placemats',
    imageClass: 'digital',
    full: '06.jpg',
    thumbs: '06.png',
  },
  {
    title: 'Watercolour portrait of bride and groom',
    imageClass: 'watercolour',
    full: '05.jpg',
    thumbs: '05.png',
  },
  {
    title: 'Personal gift ideas',
    imageClass: 'digital',
    full: '08.jpg',
    thumbs: '08.png',
  },
  {
    title: 'Wedding portrait',
    imageClass: 'watercolour',
    full: '06.jpg',
    thumbs: '06.png',
  },
  {
    title: 'Christening mini tag',
    imageClass: 'event',
    full: '02.jpg',
    thumbs: '02.png',
  },
  {
    title: 'Birthday cake illustration',
    imageClass: 'cakes',
    full: '04.jpg',
    thumbs: '04.png',
  },
  {
    title: 'Kitchen tea invitation',
    imageClass: 'event',
    full: '04.jpg',
    thumbs: '04.png',
  },
  {
    title: 'Bridal shower invitation',
    imageClass: 'event',
    full: '09.jpg',
    thumbs: '09.png',
  },
  {
    title: 'Watercolour portrait of couple',
    imageClass: 'watercolour',
    full: '07.jpg',
    thumbs: '07.png',
  },
  {
    title: 'Live illustrations by Christina',
    imageClass: 'live',
    full: '02.jpg',
    thumbs: '02.png',
  },
  {
    title: 'Live illustrations by Christina',
    imageClass: 'live',
    full: '06.jpg',
    thumbs: '06.png',
  },
  {
    title: 'Bridal party announcement card',
    imageClass: 'announcement',
    full: '05.jpg',
    thumbs: '05.png',
  },
  {
    title: 'Live fashion illustrations',
    imageClass: 'live',
    full: '04.jpg',
    thumbs: '04.png',
  },
  {
    title: 'Birthday cake illustration',
    imageClass: 'cakes',
    full: '08.jpg',
    thumbs: '08.png',
  },
  {
    title: 'Bridal shower event card',
    imageClass: 'event',
    full: '07.jpg',
    thumbs: '07.png',
  },
  {
    title: 'Birthday cake illustration',
    imageClass: 'cakes',
    full: '07.jpg',
    thumbs: '07.png',
  },
  {
    title: 'Birthday cake illustration',
    imageClass: 'cakes',
    full: '02.jpg',
    thumbs: '02.png',
  },
  {
    title: 'Wedding save the date invitation',
    imageClass: 'announcement',
    full: '01.jpg',
    thumbs: '01.png',
  },
  {
    title: 'Bridal party announcement card',
    imageClass: 'announcement',
    full: '03.jpg',
    thumbs: '03.png',
  },
  {
    title: 'Framed digital illustration',
    imageClass: 'digital',
    full: '01.jpg',
    thumbs: '01.png',
  },
  {
    title: 'Event placement cards',
    imageClass: 'digital',
    full: '09.jpg',
    thumbs: '09.png',
  },
  {
    title: 'Bridal shower welcome card',
    imageClass: 'digital',
    full: '10.jpg',
    thumbs: '10.png',
  },
  {
    title: 'Baby shower welcome card',
    imageClass: 'digital',
    full: '11.jpg',
    thumbs: '11.png',
  },
  {
    title: 'Digital portrait',
    imageClass: 'digital',
    full: '02.jpg',
    thumbs: '02.png',
  },
  {
    title: 'Watercolour portrait of bride and groom',
    imageClass: 'watercolour',
    full: '08.jpg',
    thumbs: '08.png',
  },
  {
    title: 'Hens party welcome card',
    imageClass: 'digital',
    full: '03.jpg',
    thumbs: '03.png',
  },
  {
    title: 'Framed watercolour portrait',
    imageClass: 'watercolour',
    full: '01.jpg',
    thumbs: '01.png',
  },
  {
    title: 'Watercolour portrait mother and daughter',
    imageClass: 'watercolour',
    full: '02.jpg',
    thumbs: '02.png',
  },
  {
    title: 'Puppy watercolour portrait',
    imageClass: 'watercolour',
    full: '03.jpg',
    thumbs: '03.png',
  },
  {
    title: 'Bridal shower welcome card',
    imageClass: 'live',
    full: '03.jpg',
    thumbs: '03.png',
  },
];

export { galleryImages as default }
